services:
  fva:
    image: fva
    depends_on:
      - "app_db"
    container_name: fva
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=app_db;Port=5432;Database=ODIN; Integrated Security=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
  app_db:
    image: postgres:latest
    container_name: odin_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=odin_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
volumes:
  app_data: