@FVA_HostAddress = https://localhost:8081

GET {{FVA_HostAddress}}/health/
Accept: text/plain

### Get Organisation
GET {{FVA_HostAddress}}/api/Organisation
Accept: text/plain

### Get location
GET {{FVA_HostAddress}}/api/Location

### Seed
GET {{FVA_HostAddress}}/seed
